// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbXDbrFrPMnUbCU3PlN5_pNBRnmpNP5Q',
    appId: '1:794786710321:web:286f971ea9248ca286e610',
    messagingSenderId: '794786710321',
    projectId: 'final-harmo',
    authDomain: 'final-harmo.firebaseapp.com',
    databaseURL: 'https://final-harmo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-harmo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0Kz9Zq3Ii2Lg6YKVRVn_hgN8ifJeE1k',
    appId: '1:794786710321:android:2fb1daa046fab38386e610',
    messagingSenderId: '794786710321',
    projectId: 'final-harmo',
    databaseURL: 'https://final-harmo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-harmo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApNCt8HxNtmUSU3s61j4BymMR19WIRh_M',
    appId: '1:794786710321:ios:5c66ae8ad8f986bf86e610',
    messagingSenderId: '794786710321',
    projectId: 'final-harmo',
    databaseURL: 'https://final-harmo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-harmo.appspot.com',
    iosBundleId: 'com.example.finals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApNCt8HxNtmUSU3s61j4BymMR19WIRh_M',
    appId: '1:794786710321:ios:9776cd9a5163a44a86e610',
    messagingSenderId: '794786710321',
    projectId: 'final-harmo',
    databaseURL: 'https://final-harmo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-harmo.appspot.com',
    iosBundleId: 'com.example.finals.RunnerTests',
  );
}
